import type { DisableMatrixDef } from "@domain/public";

/**
 * What every status refuses, ends, and closes: the disable matrix page's table, cell for
 * cell, so a changed cell is changed on the page and here together. Every status definition
 * sits in exactly one row. A unit wears a row while every flag the row is worn by is raised on
 * it, unless a row worn by those flags and more is worn too, and answers each cell with the
 * strictest row it wears. Lift is worn by `lifted` with the `stunned` it raises, so it covers
 * stun, and refuses with `stunned`, since the stun it carries is what the player is told. The
 * rows run in the order a refusal's reason is chosen by: stun, lift, silence, root, disarm,
 * then the rows that refuse nothing.
 */
export const disableMatrix = [
  {
    id: "stun",
    statuses: ["stun"],
    flags: ["stunned"],
    wornBy: ["stunned"],
    reason: "stunned",
    cells: {
      q: "refused",
      w: "refused",
      e: "refused",
      r: "refused",
      d: "refused",
      f: "refused",
      move: "cancelled",
      attackTarget: "cancelled",
      attackMove: "cancelled",
      stop: "refused",
      castPoint: "cancelled",
      targetingCursor: "closed",
      attackMoveCursor: "closed",
    },
  },
  {
    id: "lift",
    statuses: ["lift", "updraft_lift"],
    flags: ["lifted", "stunned", "untargetable"],
    wornBy: ["lifted", "stunned"],
    reason: "stunned",
    cells: {
      q: "refused",
      w: "refused",
      e: "refused",
      r: "refused",
      d: "refused",
      f: "refused",
      move: "refused",
      attackTarget: "refused",
      attackMove: "refused",
      stop: "refused",
      castPoint: "cancelled",
      targetingCursor: "closed",
      attackMoveCursor: "closed",
    },
  },
  {
    id: "silence",
    statuses: ["silence"],
    flags: ["silenced"],
    wornBy: ["silenced"],
    reason: "silenced",
    cells: {
      q: "refused",
      w: "refused",
      e: "refused",
      r: "refused",
      d: "refused",
      f: "refused",
      move: "allowed",
      attackTarget: "allowed",
      attackMove: "allowed",
      stop: "allowed",
      castPoint: "continues",
      targetingCursor: "closed",
      attackMoveCursor: "continues",
    },
  },
  {
    id: "root",
    statuses: ["root"],
    flags: ["rooted"],
    wornBy: ["rooted"],
    reason: "rooted",
    cells: {
      q: "allowed",
      w: "allowed",
      e: "allowed",
      r: "allowed",
      d: "allowed",
      f: "allowed",
      move: "cancelled",
      attackTarget: "allowed",
      attackMove: "cancelled",
      stop: "allowed",
      castPoint: "continues",
      targetingCursor: "continues",
      attackMoveCursor: "continues",
    },
  },
  {
    id: "disarm",
    statuses: ["disarm"],
    flags: ["disarmed"],
    wornBy: ["disarmed"],
    reason: "disarmed",
    cells: {
      q: "allowed",
      w: "allowed",
      e: "allowed",
      r: "allowed",
      d: "allowed",
      f: "allowed",
      move: "allowed",
      attackTarget: "refused",
      attackMove: "allowed",
      stop: "allowed",
      castPoint: "continues",
      targetingCursor: "continues",
      attackMoveCursor: "continues",
    },
  },
  {
    id: "slow",
    statuses: ["slow", "wane_chill", "wane"],
    flags: ["aggro_hidden"],
    wornBy: [],
    reason: null,
    cells: {
      q: "allowed",
      w: "allowed",
      e: "allowed",
      r: "allowed",
      d: "allowed",
      f: "allowed",
      move: "allowed",
      attackTarget: "allowed",
      attackMove: "allowed",
      stop: "allowed",
      castPoint: "continues",
      targetingCursor: "continues",
      attackMoveCursor: "continues",
    },
  },
  {
    id: "damage_over_time",
    statuses: ["burn", "glacier_chill"],
    flags: [],
    wornBy: [],
    reason: null,
    cells: {
      q: "allowed",
      w: "allowed",
      e: "allowed",
      r: "allowed",
      d: "allowed",
      f: "allowed",
      move: "allowed",
      attackTarget: "allowed",
      attackMove: "allowed",
      stop: "allowed",
      castPoint: "continues",
      targetingCursor: "continues",
      attackMoveCursor: "continues",
    },
  },
  {
    id: "knockback",
    statuses: ["knockback", "charge"],
    flags: ["displaced"],
    wornBy: ["displaced"],
    reason: null,
    cells: {
      q: "allowed",
      w: "allowed",
      e: "allowed",
      r: "allowed",
      d: "allowed",
      f: "allowed",
      move: "allowed",
      attackTarget: "allowed",
      attackMove: "allowed",
      stop: "allowed",
      castPoint: "continues",
      targetingCursor: "continues",
      attackMoveCursor: "continues",
    },
  },
  {
    id: "no_disable",
    statuses: ["quicken", "self_heal", "hoarfrost", "bash", "frost_attack"],
    flags: [],
    wornBy: [],
    reason: null,
    cells: {
      q: "allowed",
      w: "allowed",
      e: "allowed",
      r: "allowed",
      d: "allowed",
      f: "allowed",
      move: "allowed",
      attackTarget: "allowed",
      attackMove: "allowed",
      stop: "allowed",
      castPoint: "continues",
      targetingCursor: "continues",
      attackMoveCursor: "continues",
    },
  },
] as const satisfies DisableMatrixDef;
